CREATE DATABASE IF NOT EXISTS XYZZ;
USE XYZZ;
CREATE TABLE IF NOT EXISTS INFO(
 NAME VARCHAR(79) NOT NULL,
 SALARY INT NOT NULL
);
INSERT INTO INFO
(NAME , SALARY)
VALUES
("ADAM",250000),
("BOB",30000),
("CASEY",40000);
SELECT * FROM INFO;
