CREATE DATABASE IF NOT EXISTS TOTALPAYMENT;
USE TOTALPAYMENT;
CREATE TABLE IF NOT EXISTS PAYMENT(
 CUSTOMER_ID  INT PRIMARY KEY,
 CUSTOMER VARCHAR(90),
 MODE VARCHAR(89),
 CITY VARCHAR(89)
);
INSERT INTO PAYMENT
(CUSTOMER_ID,CUSTOMER,MODE, CITY)
VALUES
(101,"OLIVIA BARRETT","NETBANKING","PORTLAND"),
(102,"ETHAN SINCLAIR","CREDIT CARD","MIAMI"),
(103,"MAYA HERNANDEZ","CREDIT CARD","SEATTLE"),
(104,"LIAM DONOVAN","NETBANKING","DENVER"),
(105,"SOPHIA NGUYEN","CREDIT CARD","NEW ORLEANS"),
(106,"CALEB FOSTER","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA PATEL","DEBIT CARD","PHOENIX"),
(108,"LUCAS CARTER","NETBANKING","BOSTON"),
(109,"ISABELLA","NETBANKING","NASHVILLE"),
(110,"JACKSON BROOKS","CREDIT CARD","BOSTON");

SELECT MODE,COUNT(MODE)
FROM PAYMENT
GROUP BY MODE;