CREATE DATABASE IF NOT EXISTS AAA;
USE AAA;
CREATE TABLE IF NOT EXISTS TEMP1(
 ID INT,
 NAME VARCHAR(79),
 AGE INT,
 CITY VARCHAR(45),
 PRIMARY KEY ( ID, NAME)
);
CREATE TABLE IF NOT EXISTS EMP(
ID INT,
SALARY INT DEFAULT 240000);
INSERT INTO EMP (ID) VALUES (101);
SELECT * FROM EMP;