CREATE DATABASE IF NOT EXISTS COLLEGE30457;
USE COLLEGE30457;
CREATE TABLE IF NOT EXISTS  STUDENT34(
  id INT ,
  name  varchar(90) not null
);
INSERT INTO STUDENT34
(id,name)
VALUES
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");

CREATE TABLE COURSE(
  id INT ,
  COURSE VARCHAR(90)

);
INSERT INTO COURSE
(id , COURSE)
VALUES
(102,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"COMPUTER SCIENCE");


SELECT * FROM STUDENT34 AS S
RIGHT JOIN COURSE AS C
ON S.id = C.id
UNION
SELECT*FROM STUDENT34 AS S
LEFT JOIN COURSE AS C
ON S.id = C.id
where c.id=s.id;
