CREATE DATABASE IF NOT EXISTS COLLEGEtt;
USE COLLEGEtt;
CREATE TABLE IF NOT EXISTS  STUDENTtt(
  student_id INT ,
  name  varchar(90) not null
);
INSERT INTO STUDENTtt
(student_id,name)
VALUES
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");

CREATE TABLE COURSE(
  STUDENT_ID INT ,
  COURSE VARCHAR(90)

);
INSERT INTO COURSE
(STUDENT_ID , COURSE)
VALUES
(102,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"COMPUTER SCIENCE");

SELECT * FROM COURSE




SELECT * FROM STUDENTTT AS S
INNER JOIN COURSE AS C
ON S.STUDENT_ID = C.STUDENT_ID

SELECT * FROM STUDENTTT AS S
LEFT JOIN COURSE AS C
ON S.STUDENT_ID = C.STUDENT_ID

SELECT *FROM STUDENTTT AS S
RIGHT JOIN COURSE AS C
ON S.STUDENT_ID = C.STUDENT_ID


SELECT * FROM STUDENTTT AS S
LEFT JOIN COURSE AS C
ON S.STUDENT_ID = C.STUDENT_ID
UNION
SELECT *FROM STUDENTTT AS S
RIGHT JOIN COURSE AS C
ON S.STUDENT_ID = C.STUDENT_ID

SELECT * FROM STUDENTTT AS S
LEFT JOIN COURSE AS C
ON S.STUDENTTT_ID = C.STUDENTTT_ID
WHERE C.COURSE_ID IS NULL

SELECT * FROM STUDENTTT AS S
RIGHT JOIN COURSE AS C
ON S.STUDENTTT_ID = C.STUDENTTT_ID
WHERE C.STUDENTTT_ID IS NULL;



