CREATE  DATABASE IF NOT EXISTS OLLEGE;
USE COLLEGE;

CREATE TABLE IF NOT EXISTS STUDENT(
 ROLLNO INT PRIMARY KEY,
 NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(20)
);
INSERT INTO  STUDENT
(ROLLNO, NAME, MARKS, GRADE, CITY)
VALUES
(101,"ANIL",78,"C","PUNE"),
(102,"BHUMIKA",93,"A","MUMBAI"),
(103,"CHETAN",85,"B","MUMBAI"),
(104,"DHRUV",96,"A","DELHI"),
(105,"EMENUEL",12,"F","DELHI"),
(106,"FARAH",82,"B","DELHI");

SELECT * FROM STUDENT;
SELECT NAME , MARKS FROM STUDENT;
SELECT DISTINCT CITY FROM STUDENT; 

SELECT * FROM STUDENT WHERE MARKS >90;
SELECT* FROM STUDENT WHERE CITY = 'MUMBAI';

SELECT * FROM STUDENT 
WHERE MARKS > 90 AND CITY = "MUMBAI";

SELECT * FROM STUDENT 
WHERE MARKS > 100 OR CITY = "MUMBAI";

SELECT * FROM STUDENT 
WHERE MARKS BETWEEN 80 AND 90;

SELECT * FROM STUDENT 
WHERE CITY IN ("DELHI" , "MUMBAI");

SELECT * FROM STUDENT 
WHERE CITY  NOT IN ("DELHI" , "MUMBAI");

SELECT * FROM STUDENT 
WHERE MARKS +10 > 100 ;

SELECT * FROM STUDENT 
WHERE MARKS = 93;

SELECT * FROM STUDENT 
WHERE MARKS > 9
 LIMIT 3;
 
 SELECT * FROM STUDENT 
 ORDER BY MARKS ASC;
 
  SELECT * FROM STUDENT 
 ORDER BY MARKS DESC
 LIMIT 3;
 
 




