CREATE DATABASE QS;
USE QS;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(87) NOT NULL,
MARKS INT NOT NULL,
GRADE VARCHAR(1) NOT NULL
);
INSERT INTO STUDENT
(ID,NAME,MARKS,GRADE)
VALUES
(101,"RAM",99,"O"),
(102,"SAM",87,"A"),
(103,"PAM",98,"O");
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
CHANGE COLUMN NAME FULL_NAME VARCHAR(89) NOT NULL;

ALTER TABLE STUDENT 
DROP COLUMN GRADE;


DELETE FROM STUDENT 
 WHERE MARKS < 80;
